[general]
save_time = 60
hype_emote = "iamhar2Bob"
ignored_users = ["iamhardbot", "pretzelrocks"]

[points]
ticks_per_message = 10
points_per_tick = 1
tick_speed = 6
steal_chance = 0.001
steal_min = 1
steal_max = 10

[variables]
ARCTIC = "Look what @ArcticSpaceFox made: iamhar2Bob iamhar2Energy"
TOGGLEBIT = "https://www.twitch.tv/togglebit"
NRT = "https://www.twitch.tv/neonraytracer"
BROOKS = "https://www.twitch.tv/brookzerker"
GITHUB = "https://github.com/hardliner66"
DOTFILES = "https://github.com/hardliner66/scripts"
DISCORD = "https://discord.gg/nbuGqpA"
BEGIN = "https://www.twitch.tv/beginbot"

[commands]
"ping" = "pong"
"bob" = "iamhar2Bob"
"energy" = "iamhar2Energy"
"lul" = "LUL"
"os" = "Hardliner is using Manjaro btw."
"beginbot" = { value = "$BEGIN", aliases = ["begin"] }
"github" = { value = "$GITHUB", aliases = ["git", "gh"] }
"togglebit" = { value = "$TOGGLEBIT", aliases = ["toggle"] }
"neonraytracer" = { value = "$NRT", aliases = ["nrt"] }
"brookzerker" = { value = "$BROOKS", aliases = ["brooks"] }
"arcticspacefox" = { value = "$ARCTIC", aliases = ["arctic"] }
"dotfiles" = { value = "$DOTFILES", aliases = ["dot", "scripts"] }
"discord" = { value = "$DISCORD", aliases = ["dc"] }

[auto_commands]
time = 300
commands = ["dc", "dot", "arctic"]

[groups.admin]
users = ["iamhardliner"]

[groups.mod]
users = ["arcticspacefox"]
